title: Teambuilding
updated_by: c3156d07-bd3b-4b0e-8dc5-9cb5f495810c
updated_at: 1716469855
blueprint: formule_category
price_adult: 20.0
available_days:
  -
    id: lwj9toea
    date: '2024-05-28'
  -
    id: lwj9tv0j
    date: '2024-05-30'
