title: Teambuilding
updated_by: c3156d07-bd3b-4b0e-8dc5-9cb5f495810c
updated_at: 1717529634
blueprint: formule_category
tijdstip:
  - '0u00 - 1u30'
  - '1u30 - 3u00'
  - '3u00 - 4u30'
  - '4u30 - 6u00'
  - '6u00 - 7u30'
  - '7u30 - 9u00'
  - '9u00 - 10u30'
available_days:
  -
    id: lwly1w29
    date: '2024-06-11'
  -
    id: lx0ssjcj
    date: '2024-06-13'
fixed_days:
  - di
  - do
