title: Weekendvaren
updated_by: c3156d07-bd3b-4b0e-8dc5-9cb5f495810c
updated_at: 1717582602
blueprint: formule_category
price_adult: 15.0
price_children: 5.0
tijdstip:
  - '13u30 - 15u00'
  - '15u00 - 16u30'
  - '16u30 - 18u00'
  - '18u00 - 19u30'
  - '19u30 - 21u00'
  - '21u00 - 22u30'
  - '22u30 - 00u00'
grid_field:
  -
    id: lwj9jvl9
    date_field: '2024-05-25'
dagen:
  -
    id: lwj9nzux
    available_days: '2024-05-25'
fixed_days:
  - za
  - zo
not_available:
  -
    id: lx0z2ty0
    days: '2024-06-08'
    date: '2024-06-08'
  -
    id: lx0z33j5
    days: '2024-06-15'
    date: '2024-06-15'
available_days:
  -
    id: lx1l1x0f
    date: '2024-06-04'
